version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/inventorymgmt-1.0-SNAPSHOT.jar
    - appspec.yml
    - rds-ca*.pem
    - Procfile
  discard-paths: yes